zoo:
  # Attack instance parameters
  confidence: 0.25
  learning_rate: 0.1
  binary_search_steps: 10
  initial_const: 0.001
  abort_early: True
  use_resize: False
  use_importance: False
  variable_h: 0.3
  targeted: False
  nb_parallel: 5
  batch_size: 1
  verbose: True
  max_iter: 5

xgb:
  # Tree booster params
  eta: 0.3
  gamma: 0
  max_depth: 6
  min_child_weight: 1
  tree_method: exact
  objective: multi:softprob

dataset: data/large_norm.csv
out: result/large_regular.yaml
folds: 5 # K-folds
iter: 2  # Attack iters

validate: false
immutable: [ 0,  1,  2,  6,  7,  8,  10,  11,  12,  13 ]
constraints:
  3: "lambda x: (x * 502) <= 5.0"
  17: "lambda x: round(x * 168910, 0) in [0, 40, 76, 131, 380, 456, 562, 563, 589, 100982, 114431, 110715]"
