dataset: data/small_norm.csv
out: result/small_const.yaml
fig: result/small_const_graph.pdf
validate: true

immutable: [ 4, 5, 6, 7 ]
constraints:
  0: "lambda x: x == 0 or x == 1"
  1: "lambda x: (x * 502) <= 5.0"
