dataset: data/large_norm.csv
out: result/large_const.yaml
validate: true

immutable: [ 10,  11,  12,  13 ]
constraints:
  0: [ [ 1, 2 ], "lambda x: sum(x) == 1" ]
  1: [ [ 0, 2 ], "lambda x: sum(x) == 1" ]
  2: [ [ 0, 1 ], "lambda x: sum(x) == 1" ]
  6: [ [ 7, 8, 1, 16, 17 ],
       "lambda x: sum(x[0:2]) == 1 and 
       (x[0] != 1 or x[3] != 1 or (x[4] == 0 and x[5] == 0))" ]
  7: [ [ 6, 8 ], "lambda x: sum(x) == 1" ]
  8: [ [ 6, 7 ], "lambda x: sum(x) == 1" ]
  14: [ [ 1, 2, 16, 8, 15, 17, 11, 7 ],
        "lambda x: 
        (x[1] != 1 or x[0] >= x[3] or x[4] == 1 or x[5] < x[6]) and 
        (x[2] != 1 or (x[0] >= x[3] or (x[8] == 1 and x[7] == 1)) and 
        (x[0] < x[3] or (x[8] == 1 or x[5] < x[6])))" ]
  15: [ [ 1, 14 ],
        "lambda x: x[1] != 1 or 
        (x[2] <= x[0] and (x[2] == 0 or x[0] >= 20))" ]
  17: [ [ 1, 16 ],
        "lambda x: x[1] != 1 or 
        (x[2] <= x[0] and (x[2] == 0 or x[0] >= 20))" ]

#   0 --- proto=udp
#   1 --- proto=tcp
#   2 --- proto=icmp
#   3 --- duration
#   4 --- orig_bytes
#   5 --- resp_bytes
#   6 --- conn_state=S0
#   7 --- conn_state=SF
#   8 --- conn_state=other
#   9 --- missed_bytes
#  10 --- history=D
#  11 --- history=Dd
#  12 --- history=S
#  13 --- history=other
#  14 --- orig_pkts
#  15 --- orig_ip_bytes
#  16 --- resp_pkts
#  17 --- resp_ip_bytes
#  18 --- label