zoo:
  # Attack instance parameters
  confidence: 0.25
  learning_rate: 0.1
  binary_search_steps: 10
  initial_const: 0.001
  abort_early: True
  use_resize: False
  use_importance: False
  variable_h: 0.3
  targeted: False
  nb_parallel: 5
  batch_size: 1
  verbose: True
  max_iter: 5

xgb:
  # Tree booster params
  eta: 0.3
  gamma: 0
  max_depth: 6
  min_child_weight: 1
  tree_method: exact
  objective: multi:softprob

dataset: data/small_norm.csv
out: result/small_const.yaml
folds: 5 # K-folds
iter: 3  # Attack iters

validate: true
immutable: [ 4, 5, 6, 7 ]
constraints:
  0: "lambda x: x == 0 or x == 1"
  1: "lambda x: (x * 502) <= 5.0"
