dataset: data/large_norm.csv
out: result/large_regular.yaml
fig: result/large_regular_graph.pdf
validate: false

immutable: [ 0,  1,  2,  6,  7,  8,  10,  11,  12,  13 ]
constraints:
  3: "lambda x: (x * 502) <= 5.0"
  17: "lambda x: round(x * 168910, 0) in [0, 40, 76, 131, 380, 456, 562, 563, 589, 100982, 114431, 110715]"
