dataset: data/ctu_1-8-34.csv
name: IoT-23
desc: sampled from IoT-23 malware captures 1-1, 8-1, 34-1
iter: 2

immutable: [ 0, 1, 2, 6, 7, 8, 10, 11, 12, 13 ]

#   0 --- proto=udp
#   1 --- proto=tcp
#   2 --- proto=icmp
#   3 --- duration
#   4 --- orig_bytes
#   5 --- resp_bytes
#   6 --- conn_st=S0
#   7 --- conn_st=SF
#   8 --- conn_st=other
#   9 --- missed_bytes
#  10 --- history=D
#  11 --- history=Dd
#  12 --- history=S
#  13 --- history=other
#  14 --- orig_pkts
#  15 --- orig_ip_bytes
#  16 --- resp_pkts
#  17 --- resp_ip_bytes
#  18 --- label

constraints:
  14: [ [ 0, 1, 6, 7, 8, 11, 15, 16, 17 ],
    "lambda a: a[0] <= a[7] 
         and ((a[2] != 1) or a[0] == 0 or a[7] > 20)
         and ((a[2] != 1) or a[0] >= a[8] or a[5] != 1 or a[7] < a[9])
         and ((a[2] == 1) or a[3] != 1 or (a[8] == 0 and a[9] == 0))
         and ((a[1] != 1) or a[0] >= a[8] or (a[6] == 1 and a[4] == 1))
         and ((a[1] != 1) or a[0] < a[8] or a[7] >= a[9] or a[4] == 1)" ]
  15: [ [ 14 ],
        "lambda a: a[0] > a[1]" ]
  16: [ [ 1, 6, 17 ],
    "lambda a: a[0] <= a[3]
         and ((a[1] == 1) or a[2] != 1 or (a[0] == 0 and a[3] == 0))
         and ((a[1] != 1) or a[2] != 1 or (a[0] == 0 and a[3] == 0))
         and ((a[1] != 1) or a[0] == 0 or a[3] >= 20)" ]
  17: [ [ 16 ],
        "lambda a: a[0] > a[1]" ]
