name: test
dataset: data/ctu_44-1.csv
desc: IoT23 Malware-Capture-44-1

constraints:
  immutable:
    - conn_state=SF
    - conn_state=S0
    - conn_state=OTH
    - conn_state=S1
  predicates:
    - proto=udp == 0 or proto=udp == 1
    - duration <= 23.0 or 150 <= duration <= 200 or duration > 300
    - proto=udp == 0 or orig_bytes <= resp_bytes
