dataset: data/test.csv
name: test
desc: IoT23 Malware-Capture-44-1

constraints:
  conn_state=SF: False
  conn_state=S0: False
  conn_state=OTH: False
  conn_state=S1: False
  proto=udp: "proto=udp == 0 or proto=udp == 1"
  duration: "(duration * 502) <= 23.0 or duration == 1"
