dataset: data/unsw_nb15.csv
name: UNSW NB15
desc: sampled from 175K training set
iter: 2

constraints:
  proto=tcp : False
  proto=udp : False
  proto=other : False
  service=- : False
  service=http : False
  service=dns : False
  service=other : False
  state=FIN : False
  state=INT : False
  state=other : False

