name: UNSW-NB15
dataset: data/unsw_nb15.csv
desc: sampled from 175K training set

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

#This is UNSW Constraints
constraints:
  proto_tcp: False
  proto_udp: False
  proto_other: False
  service_none: False
  service_http: False
  service_dns: False
  service_other: False
  state_FIN: False
  state_INT: False
  state_other: False
  swin: >
       ((proto_tcp != 1) or (swin == 255 or dwin == 255) or (dbytes == 0 and dwin == 0) or state_FIN==1)
       and (proto_tcp == 1 or (swin == 0 and dwin == 0 and stcpb == 0 and dtcpb == 0))
  dwin: >
       ((proto_tcp != 1) or (swin == 255 or dwin == 255) or (dbytes == 0 and dwin == 0) or state_FIN==1)
       and (proto_tcp == 1 or (swin == 0 and dwin == 0 and stcpb == 0 and dtcpb == 0))
  dur: >
      (proto_tcp != 1 or state_FIN == 1 or dur == 0 or state_INT != 1 or dbytes == 0)
  dbytes: >
      (proto_tcp != 1 or state_FIN == 1 or dur == 0 or state_INT != 1 or dbytes == 0)
