dataset: data/unsw_nb15.csv
name: UNSW NB15
desc: sampled from 175K training set
iter: 2

constraints:
  proto_tcp: False
  proto_udp: False
  proto_other: False
  service_none: False
  service_http: False
  service_dns: False
  service_other: False
  state_FIN: False
  state_INT: False
  state_other: False

