name: UNSW2-NB15
dataset: data/unsw_nb15.csv
desc: sampled from 175K training set, immutable categorical attrs.

dnn:
  layers: [ 64, 64, 32 ]

cpgd:
  feat_file: "data/feature_unsw.csv"

constraints:
  predicates:
    - proto_tcp + proto_udp + proto_other == 1
    - service_none + service_http + service_dns + service_other == 1
    - state_FIN + state_INT + state_other == 1
    - proto_tcp != 1 or (swin == 255 or dwin == 255) or (dbytes == dwin == 0) or state_FIN==1
    - proto_tcp != 1 or state_FIN == 1 or dur == 0 or state_INT != 1 or dbytes == 0
    - proto_tcp == 1 or (swin == dwin == stcpb == dtcpb == 0)
    #  I added more constraints:
    - state_INT != 1 or (sbytes > 0 and dbytes == 0)
    - (service_dns != 1 and proto_udp != 1) or smean <= 512
    # If window size is represented as 8 bits field, then swin and dwin should be in this range: [0,255]
    - swin >= 0 and swin <= 255
    - dwin >= 0 and dwin <= 255
    - sloss >= 0 and sloss <= 3993
    - dloss >= 0 and dloss <= 2627
